
ALTER TABLE shop_products 
ADD COLUMN IF NOT EXISTS max_installments INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS interest_rate DECIMAL(5,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS installment_price DECIMAL(10,2) DEFAULT NULL;
