-- Inserir templates de exemplo para o sistema de catálogo de serviços

-- Template 1: Samsung A06 - Troca de Tela - Original Nacional
INSERT INTO budgets (
  owner_id,
  client_name,
  device_model,
  device_type,
  part_quality,
  issue,
  cash_price,
  installment_price,
  total_price,
  installments,
  warranty_months,
  includes_delivery,
  includes_screen_protector,
  custom_services,
  notes,
  valid_until,
  workflow_status
) VALUES (
  '88e717ac-d5ca-4dd9-ac4e-4b3116c7d97c',
  'TEMPLATE',
  'Samsung A06',
  'Smartphone',
  'Troca de Tela',
  'Original Nacional',
  35000,
  38000,
  38000,
  4,
  6,
  true,
  true,
  'Busca e entrega • Película 3D de brinde',
  'Entrega no mesmo dia',
  '2025-10-31',
  'template'
);

-- Template 2: Samsung A06 - Troca de Tela - Original Importada
INSERT INTO budgets (
  owner_id,
  client_name,
  device_model,
  device_type,
  part_quality,
  issue,
  cash_price,
  installment_price,
  total_price,
  installments,
  warranty_months,
  includes_delivery,
  includes_screen_protector,
  custom_services,
  notes,
  valid_until,
  workflow_status
) VALUES (
  '88e717ac-d5ca-4dd9-ac4e-4b3116c7d97c',
  'TEMPLATE',
  'Samsung A06',
  'Smartphone',
  'Troca de Tela',
  'Original Importada',
  25000,
  28000,
  28000,
  4,
  3,
  true,
  true,
  'Busca e entrega • Película 3D de brinde',
  'Entrega no mesmo dia',
  '2025-10-31',
  'template'
);

-- Template 3: iPhone 15 Pro Max - Troca de Bateria - Original Apple
INSERT INTO budgets (
  owner_id,
  client_name,
  device_model,
  device_type,
  part_quality,
  issue,
  cash_price,
  installment_price,
  total_price,
  installments,
  warranty_months,
  includes_delivery,
  includes_screen_protector,
  custom_services,
  notes,
  valid_until,
  workflow_status
) VALUES (
  '88e717ac-d5ca-4dd9-ac4e-4b3116c7d97c',
  'TEMPLATE',
  'iPhone 15 Pro Max',
  'Smartphone',
  'Troca de Bateria',
  'Original Apple',
  80000,
  85000,
  85000,
  6,
  12,
  false,
  false,
  'Teste de saúde da bateria • Limpeza interna completa',
  'Bateria com capacidade de 100%',
  '2025-12-31',
  'template'
);

-- Template 4: iPhone 15 Pro Max - Troca de Bateria - Premium Compatível
INSERT INTO budgets (
  owner_id,
  client_name,
  device_model,
  device_type,
  part_quality,
  issue,
  cash_price,
  installment_price,
  total_price,
  installments,
  warranty_months,
  includes_delivery,
  includes_screen_protector,
  custom_services,
  notes,
  valid_until,
  workflow_status
) VALUES (
  '88e717ac-d5ca-4dd9-ac4e-4b3116c7d97c',
  'TEMPLATE',
  'iPhone 15 Pro Max',
  'Smartphone',
  'Troca de Bateria',
  'Premium Compatível',
  45000,
  49000,
  49000,
  4,
  6,
  false,
  false,
  'Teste de saúde da bateria • Limpeza interna completa',
  'Bateria com capacidade de 100%',
  '2025-12-31',
  'template'
);