-- 1. Enable pg_trgm extension for fuzzy search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Add GIN Indexes for fast text search
-- Clients: Name
CREATE INDEX IF NOT EXISTS idx_clients_name_trgm ON clients USING GIN (name gin_trgm_ops);

-- Chronic Problems: Device Model and Symptom
CREATE INDEX IF NOT EXISTS idx_chronic_device_trgm ON chronic_problems USING GIN (device_model gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_chronic_symptom_trgm ON chronic_problems USING GIN (symptom gin_trgm_ops);

-- Budgets: Client Name (for admin search)
CREATE INDEX IF NOT EXISTS idx_budgets_client_name_trgm ON budgets USING GIN (client_name gin_trgm_ops);

-- 3. Add GIN Indexes for JSONB columns in Stores (for filtering by config/policies)
CREATE INDEX IF NOT EXISTS idx_stores_contact_info ON stores USING GIN (contact_info);
CREATE INDEX IF NOT EXISTS idx_stores_policies ON stores USING GIN (policies);

-- 4. Fix Duplicate Foreign Keys in budget_parts
-- Check if both exist and drop the redundant one (budget_parts_budget_id_fkey is the autogenerated one usually)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'budget_parts_budget_id_fkey' AND table_name = 'budget_parts'
    ) AND EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_budget_parts_budget_id' AND table_name = 'budget_parts'
    ) THEN
        ALTER TABLE budget_parts DROP CONSTRAINT budget_parts_budget_id_fkey;
    END IF;
END $$;

-- 5. Create Log Cleanup Function
CREATE OR REPLACE FUNCTION cleanup_old_logs()
RETURNS void AS $$
BEGIN
    -- Delete access_logs older than 90 days
    DELETE FROM access_logs WHERE timestamp < NOW() - INTERVAL '90 days';
    
    -- Delete audit_logs older than 90 days (unless marked for retention)
    DELETE FROM audit_logs 
    WHERE created_at < NOW() - INTERVAL '90 days' 
    AND (retention_until IS NULL OR retention_until < NOW());
    
    -- Delete whatsapp_zapi_logs older than 30 days (high volume)
    DELETE FROM whatsapp_zapi_logs WHERE created_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql;

-- 6. Verify and Fix coupon_usage foreign key if possible
-- We will only add a comment for now as order_id might be polymorphic or external
COMMENT ON COLUMN coupon_usage.order_id IS 'Refers to purchase_registrations.id OR external payment provider ID. Do not enforce strict FK to budgets.';
